{{- if .Values.application.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webcolor-ingress
  labels:
    name: webcolor-ingress
spec:
  ingressClassName: {{ .Values.application.ingress.className }}
  rules:
  {{- range .Values.application.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $.Release.Name }}-web-color # ~> $ é utilizado para apontar como objeto global do "for it" baseado no range de dominio que ira ser utilizado pelo app
            port: 
              number: 80
  {{- end }}
{{- end }}