apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-color
spec:
  selector:
    app: {{ .Release.Name }}-web-color
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.application.service.type }}