apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-color:blue
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webcolor
spec:
  selector:
    app: webcolor
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webcolor-ingress
  labels:
    name: webcolor-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: webcolor.10.96.78.106.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webcolor
            port: 
              number: 80

